const frequencies = [250, 500, 1000, 2000, 3000, 4000, 6000, 8000];
const ears = ['right', 'left'];
const modalities = ['air', 'bone'];

const notch2k = [
    {
        amplitude: 15,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'right',
        frequency: 3000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'right',
        frequency: 6000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'left',
        frequency: 3000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 65,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 50,
        ear: 'left',
        frequency: 6000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 65,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 55,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'right',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
];

const normal = frequencies.reduce(function(audiogram, f) {
    return audiogram.concat(
        ears.map(ear => ({
            amplitude: Math.floor(Math.random() * 6) * 5,
            ear: ear,
            frequency: f,
            modality: 'air',
            test: 'threshold',
            stimulus: 'tone',
            masking: null,
            no_response: false,
        })),
    );
}, []);

const altNormal = [
    {
        amplitude: 0,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
];

const flat40snhl = [
    {
        amplitude: 45,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
];

const flat40chl = [
    {
        amplitude: 45,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 50,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 50,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'right',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 50,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'right',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'right',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'right',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
];

const mildSensoryPresbycusis = [
    {
        amplitude: 10,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 25,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
];

const moderatelySevereSensoryPresbycusis = [
    {
        amplitude: 10,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 25,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 80,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 95,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 70,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 90,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 90,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 75,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
];

const risingMiddleEarDysfunction = [
    {
        amplitude: 45,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 50,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'right',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 50,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'right',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'right',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
];

const flat60MixedLoss = [
    {
        amplitude: 65,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 55,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 65,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 65,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 55,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 55,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'right',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'right',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'right',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
    {
        amplitude: 45,
        ear: 'right',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 80,
        no_response: false,
    },
];

const meneires = [
    {
        amplitude: 45,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 35,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 0,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 10,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 5,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 50,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'right',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'right',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
];

const presbycusisPlusOtitis = [
    {
        amplitude: 50,
        ear: 'right',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 65,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 75,
        ear: 'right',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 85,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 95,
        ear: 'right',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'left',
        frequency: 250,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 60,
        ear: 'left',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 55,
        ear: 'left',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 70,
        ear: 'left',
        frequency: 2000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 90,
        ear: 'left',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 90,
        ear: 'left',
        frequency: 8000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'left',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 20,
        ear: 'left',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'left',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'left',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 55,
        ear: 'left',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 15,
        ear: 'right',
        frequency: 250,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 25,
        ear: 'right',
        frequency: 500,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'right',
        frequency: 1000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 40,
        ear: 'right',
        frequency: 2000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
    {
        amplitude: 55,
        ear: 'right',
        frequency: 4000,
        modality: 'bone',
        test: 'threshold',
        stimulus: 'tone',
        masking: 60,
        no_response: false,
    },
];

const incompleteKid = [
    {
        amplitude: 10,
        ear: 'right',
        frequency: 500,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 30,
        ear: 'right',
        frequency: 1000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
    {
        amplitude: 50,
        ear: 'right',
        frequency: 4000,
        modality: 'air',
        test: 'threshold',
        stimulus: 'tone',
        masking: null,
        no_response: false,
    },
];

export {
    notch2k,
    altNormal,
    normal,
    flat40snhl,
    flat40chl,
    mildSensoryPresbycusis,
    moderatelySevereSensoryPresbycusis,
    risingMiddleEarDysfunction,
    flat60MixedLoss,
    meneires,
    presbycusisPlusOtitis,
    incompleteKid,
};
